### ISSUE TITLE
Build a homepage

### ISSUE THREAD

**Issue by mariamrf** [Marija1984/Platform#1]
# Required Outcome
I, as a user, want to:
- Find a homepage when I go to the website, and
- that homepage has the website's name on it.

## Bonus Points
The webpage looks nice using (optionally Bootstrap +) plain CSS!

# Notes
It doesn't need to do anything else (yet!), just be a placeholder for things.

Resources can be found in the shared documents. Post any questions you have here though :)

**Comment by Marija1984** [comment]
Hej Mariam, I have created a simple homepage and about page. Previously, I have built the appdb that is connected to the database, I have checked the database several times and the table contains all the data I put in users form. It runs locally at http://127.0.0.1:5000/users. When I run appdb2 (home and about page), it works but I don't know how to connect those two apps :/ I will put the files to a repository so you can see them..

**Comment by mariamrf** [comment]
Cool! I can walk you through that part. But first, please add the following to your Pull Request:
- A title that describes what your pull request/code changes do.
- A description of exactly what you did (what files you added for example, why, etc)
and we can discuss there :)

**Comment by Marija1984** [comment]
Ok, did so! :)

**Comment by Marija1984** [comment]
I did it, I fixed the problem. Now I will try to implement the homepage and about page to my app..

**Comment by mariamrf** [comment]
Perfect @Marija1984! Looking forward to your updates :-)

**Comment by Marija1984** [comment]
Working on putting the files together.. Funny thing is that now when I got everything back to old, removed password and returned email, now when I run the code, it returns login with the password :D And now there is no password in a code or a database.

**Comment by mariamrf** [comment]
I'm sure you'll make it work :D But if you get stuck or have specific questions let me know!

**Comment by Marija1984** [comment]
I have tried many things, I am not sure how to do what you have explained, to have one route that only gives us a homepage and other routes for POSTing an user. I understand that in my 1st version there was one route doing two things, depending on which method we use, POST or GET. So, now we want to have those routes divided in actions, right? But I don't know how to put it to a code.. I will send you a pull request..

**Comment by mariamrf** [comment]
Addressed by #3 :) which can be merged!
